
POST http://127.0.0.1:8080/usuario HTTP/1.1
Content-Type: application/json
{
    "run_usuario":"210973826",
    "primer_nombre":"fabrizio",
    "segundo_nombre":"Ignacio",
    "ap_paterno":"morales",
    "ap_materno":"rojas",
    "telefono":"8888888888"
}

GET http://127.0.0.1:8080/usuario HTTP/1.1
Content-Type: application/json

GET http://127.0.0.1:8080/usuario/1 HTTP/1.1
Content-Type: application/json

PUT http://127.0.0.1:8080/usuario HTTP/1.1
Content-Type: application/json

DELETE http://127.0.0.1:8080/usuario HTTP/1.1
Content-Type: application/json