
POST http://127.0.0.1:5000/usuario HTTP/1.1
Content-Type: application/json

{
    "run_usuario":"220030423",
    "primer_nombre":"sebastian",
    "segundo_nombre":"jesus",
    "ap_paterno":"ososrio",
    "ap_materno":"brsvo",
    "telefono":"987654321"
}

###
GET http://127.0.0.1:5000/usuario HTTP/1.1
Content-Type: application/json

###
GET http://127.0.0.1:5000/usuario/1 HTTP/1.1
Content-Type: application/json

###
PUT http://127.0.0.1:5000/usuario HTTP/1.1
Content-Type: application/json

###
DELETE http://127.0.0.1:5000/usuario/1 HTTP/1.1
Content-Type: application/json