### Obtener todos los eventos
GET http://localhost:8080/evento
Content-Type: application/json

### Obtener evento por ID
GET http://localhost:8080/evento/1
Content-Type: application/json

### Crear evento
POST http://localhost:8080/evento
Content-Type: application/json

{
    "titulo": "Expo Tecnología",
    "asunto": "Presentación de proyectos innovadores",
    "fecha_inicio": "2026-05-20",
    "fecha_fin": "2026-05-22",
    "tipo_evento": "Tecnología"
}


### Actualizar evento
PUT http://localhost:8080/evento
Content-Type: application/json

{
    "id_evento": 1,
    "titulo": "Expo Tecnología 2026",
    "asunto": "Feria anual de innovación",
    "fecha_inicio": "2026-05-21",
    "fecha_fin": "2026-05-23",
    "tipo_evento": "Feria"
}


### Eliminar evento
DELETE http://localhost:8080/evento/1
Content-Type: application/json





### OBTENER TODOS LOS CALENDARIOS
GET http://localhost:8080/calendario
Content-Type: application/json

### OBTENER CALENDARIO POR ID
GET http://localhost:8080/calendario/1
Content-Type: application/json


### AGREGAR CALENDARIO
POST http://localhost:8080/calendario
Content-Type: application/json

{
    "fecha_inicio": "2026-05-16",
    "fecha_fin": "2026-05-20",
    "id_evento": 1
}


### ACTUALIZAR CALENDARIO
PUT http://localhost:8080/calendario
Content-Type: application/json

{
    "id_calendario": 1,
    "fecha_inicio": "2026-05-18",
    "fecha_fin": "2026-05-25",
    "id_evento": 1
}


### ELIMINAR CALENDARIO
DELETE http://localhost:8080/calendario/1
Content-Type: application/json
