#### Agregar nota
POST http://127.0.0.1:8080/nota HTTP/1.1
Content-Type: application/json

{
  "calificacion": 5.0,
  "prom_calificacion": null,
  "id_evaluacion": 2,
  "rut_usuario": "12345678-9"
}



#### Obtener notas
GET http://127.0.0.1:8080/nota HTTP/1.1
Content-Type: application/json





#### Obtener nota por id
GET http://127.0.0.1:8080/nota/1 HTTP/1.1
Content-Type: application/json



#### Actualizar nota
PUT http://127.0.0.1:8080/nota HTTP/1.1
Content-Type: application/json

{
  "id_nota": 1,
  "calificacion": 4.0
}



#### Eliminar nota
DELETE http://127.0.0.1:8080/nota/1 HTTP/1.1
Content-Type: application/json